version: "3.6"

x-build-args: &build_args
  RUST_VERSION: "1.70.0"
  APP_NAME: "service1"

services:
  service1:
    build:
      context: ./
      dockerfile: ../dockerfile.d/rust.dockerfile
      args:
        <<: *build_args
    image: "service1-development"
    ports:
      - "8080:8080"
      
networks:
  heri.life_network:
    external: true