apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service1
  name: service1-deployment
  namespace: service1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: service1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node
                operator: In
                values:
                - applicationservice
      containers:
      - image: docker.pkg.github.com/hveda/devopschallenge/service1:latest
        imagePullPolicy: IfNotPresent
        name: service1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service1
  name: service1-svc
  namespace: service1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: service1
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service1
  namespace: service1
spec:
  ingressClassName: nginx
  rules:
  - host: service1.pleno.earth
    http:
      paths:
      - backend:
          service:
            name: service1-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - service1.pleno.earth
    secretName: wildcard-pleno-earth-tls
