version: "3.6"

x-build-args: &build_args
  RUST_VERSION: "1.70.0"
  APP_NAME: "service2"

services:
  service2:
    build:
      context: ./
      dockerfile: ../dockerfile.d/rust.dockerfile
      args:
        <<: *build_args
    image: "service2-development"
    ports:
      - "8081:8081"

networks:
  pleno_network:
    external: true